<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue';
type Entity = { name: string; fullName: string; namespace: string; fingerprint: string };
type SourceProperty = { name: string; typeName: string; isNullable: boolean; isSystemManaged: boolean };
type PropertyDescriptor = { displayName?: string; description?: string; required?: boolean; maxLength?: number; defaultValue?: string; dto?: boolean; create?: boolean; update?: boolean; filter?: string; sortable?: boolean };
type Descriptor = { entity: string; profile: string; crud: { get: boolean; getList: boolean; create: boolean; update: boolean; delete: boolean }; permissions: { enabled: boolean }; defaultSorting: string; properties: Record<string, PropertyDescriptor> };
type PlannedFile = { path: string; action: string; content: string; currentContent?: string | null; diff?: string | null };
type Plan = { files: PlannedFile[]; hasConflicts: boolean };
type Execution = { succeeded: boolean; logs: string[]; plan: Plan };
type DiffLine = { current: string; generated: string; state: 'same' | 'changed' | 'added' | 'removed' };
type DescriptorResponse = { descriptor: Descriptor; format: 'yaml' | 'json'; sourceProperties: SourceProperty[]; raw: string };
const entities = ref<Entity[]>([]), project = ref(''), selectedEntity = ref<string>(), sourceProperties = ref<SourceProperty[]>([]), descriptor = ref<Descriptor>(), format = ref<'yaml' | 'json'>('yaml'), raw = ref(''), plan = ref<Plan>(), selectedPath = ref<string>(), loading = ref(false), saving = ref(false), error = ref(''), logs = ref<string[]>([]), ignoredPaths = ref<string[]>([]), overwritePaths = ref<string[]>([]);
let hydrating = false; let saveTimer: number | undefined;
const editableProperties = computed(() => sourceProperties.value.filter(property => !property.isSystemManaged));
const selectedFile = computed(() => plan.value?.files.find(file => file.path === selectedPath.value));
async function api<T>(url: string, options?: RequestInit): Promise<T> { const response = await fetch(url, options); if (!response.ok) { const body = await response.json().catch(() => ({ message: response.statusText })); throw new Error(body.message ?? response.statusText); } return response.json() as Promise<T>; }
function normalize(value: Descriptor, properties: SourceProperty[]) { value.properties ??= {}; for (const property of properties.filter(item => !item.isSystemManaged)) value.properties[property.name] ??= {}; return value; }
async function loadEntities() { loading.value = true; try { project.value = (await api<{ project: string }>('/api/project')).project; entities.value = await api<Entity[]>('/api/entities'); selectedEntity.value ??= entities.value[0]?.name; } catch (reason) { error.value = String(reason); } finally { loading.value = false; } }
async function loadDescriptor() { if (!selectedEntity.value) return; loading.value = true; error.value = ''; try { const response = await api<DescriptorResponse>(`/api/entities/${encodeURIComponent(selectedEntity.value)}/descriptor`); hydrating = true; sourceProperties.value = response.sourceProperties; descriptor.value = normalize(response.descriptor, response.sourceProperties); format.value = response.format; raw.value = response.raw; plan.value = undefined; } catch (reason) { error.value = String(reason); } finally { hydrating = false; loading.value = false; } }
async function createPlan() { if (!selectedEntity.value) return; plan.value = await api<Plan>('/api/generation/plan', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ entity: selectedEntity.value }) }); selectedPath.value = plan.value.files[0]?.path; }
async function execute(action: 'generate' | 'validate' | 'format') {
  if (!selectedEntity.value) return;
  loading.value = true; error.value = '';
  try {
    const response = await api<Execution>(`/api/generation/${action}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ entity: selectedEntity.value, ignoredPaths: ignoredPaths.value, overwritePaths: overwritePaths.value }) });
    logs.value = response.logs ?? [`${action} completed.`];
    plan.value = response.plan;
    selectedPath.value = plan.value?.files[0]?.path;
    if (!response.succeeded) error.value = `${action} failed.`;
  } catch (reason) { error.value = String(reason); } finally { loading.value = false; }
}
async function saveDescriptor() { if (!selectedEntity.value || !descriptor.value || hydrating) return; saving.value = true; error.value = ''; try { const response = await api<DescriptorResponse>(`/api/entities/${encodeURIComponent(selectedEntity.value)}/descriptor`, { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ descriptor: descriptor.value, format: format.value }) }); hydrating = true; descriptor.value = normalize(response.descriptor, sourceProperties.value); raw.value = response.raw; await createPlan(); } catch (reason) { error.value = String(reason); } finally { hydrating = false; saving.value = false; } }
async function saveRaw() { if (!selectedEntity.value) return; saving.value = true; error.value = ''; try { const response = await api<DescriptorResponse>(`/api/entities/${encodeURIComponent(selectedEntity.value)}/descriptor/raw`, { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ content: raw.value, format: format.value }) }); hydrating = true; descriptor.value = normalize(response.descriptor, sourceProperties.value); raw.value = response.raw; await createPlan(); } catch (reason) { error.value = String(reason); } finally { hydrating = false; saving.value = false; } }
function selectEntity({ key }: { key: string | number }) { selectedEntity.value = String(key); }
function typeHint(property: SourceProperty) { if (property.name.endsWith('Id')) return '引用候选'; if (property.typeName.endsWith('Status') || property.typeName.endsWith('Type')) return '枚举候选'; return ''; }
function diffLines(current?: string | null, generated?: string) {
  const left = (current ?? '').split('\n'); const right = (generated ?? '').split('\n');
  const matrix = Array.from({ length: left.length + 1 }, () => Array(right.length + 1).fill(0));
  for (let i = left.length - 1; i >= 0; i--) for (let j = right.length - 1; j >= 0; j--) matrix[i][j] = left[i] === right[j] ? matrix[i + 1][j + 1] + 1 : Math.max(matrix[i + 1][j], matrix[i][j + 1]);
  const result: DiffLine[] = []; let i = 0; let j = 0;
  while (i < left.length || j < right.length) {
    if (i < left.length && j < right.length && left[i] === right[j]) { result.push({ current: left[i++], generated: right[j++], state: 'same' }); }
    else if (j < right.length && (i === left.length || matrix[i][j + 1] >= matrix[i + 1][j])) { result.push({ current: '', generated: right[j++], state: 'added' }); }
    else { result.push({ current: left[i++], generated: '', state: 'removed' }); }
  }
  return result;
}
function keepCurrent(path: string) { if (!ignoredPaths.value.includes(path)) ignoredPaths.value.push(path); overwritePaths.value = overwritePaths.value.filter(item => item !== path); }
function overwriteCurrent(path: string) { if (!overwritePaths.value.includes(path)) overwritePaths.value.push(path); ignoredPaths.value = ignoredPaths.value.filter(item => item !== path); }
watch(selectedEntity, loadDescriptor); watch(descriptor, () => { if (hydrating || !descriptor.value) return; window.clearTimeout(saveTimer); saveTimer = window.setTimeout(saveDescriptor, 600); }, { deep: true }); onMounted(loadEntities);
</script>

<template>
  <a-card v-if="logs.length" title="执行日志" size="small"><pre class="log">{{ logs.join('\n') }}</pre></a-card>
  <a-card v-if="selectedFile?.action === 'Conflict'" title="冲突处理" size="small"><p>{{ selectedFile.diff }}</p><a-space><a-button @click="keepCurrent(selectedFile.path)">保留当前文件</a-button><a-button danger @click="overwriteCurrent(selectedFile.path)">重新生成后覆盖</a-button></a-space></a-card>
  <a-card v-if="selectedFile?.currentContent" title="行级 Diff" size="small"><div v-for="(line, index) in diffLines(selectedFile.currentContent, selectedFile.content)" :key="index" :class="['diff-line', line.state]"><code>- {{ line.current }}</code><code>+ {{ line.generated }}</code></div></a-card>
  <a-layout class="studio"><a-layout-sider width="280" theme="light"><h2>ABP Generator Studio</h2><p class="project">{{ project }}</p><a-menu :selected-keys="selectedEntity ? [selectedEntity] : []" mode="inline" @click="selectEntity"><a-menu-item v-for="entity in entities" :key="entity.name">{{ entity.fullName }}</a-menu-item></a-menu></a-layout-sider>
    <a-layout-content class="content"><a-alert v-if="error" type="error" show-icon :message="error" class="alert" /><a-space><a-button :loading="loading || saving" type="primary" @click="createPlan">生成计划</a-button><a-button :loading="loading" :disabled="!plan || plan.hasConflicts" @click="execute('generate')">生成代码</a-button><a-button :loading="loading" @click="execute('validate')">验证</a-button><a-button :loading="loading" @click="execute('format')">格式化预览</a-button><a-tag v-if="saving" color="processing">正在保存并刷新计划</a-tag><a-tag v-if="plan" :color="plan.hasConflicts ? 'red' : 'green'">{{ plan.hasConflicts ? '存在冲突' : '可安全生成' }}</a-tag></a-space>
      <a-tabs v-if="descriptor" class="top-tabs"><a-tab-pane key="properties" tab="属性元数据"><a-alert type="info" show-icon message="类型、可空与系统管理属性来自领域实体，只读；下面的设置仅写入 .codegen.yaml/json。" /><a-table :data-source="editableProperties" :pagination="false" row-key="name" size="small" :scroll="{ x: 1500 }" class="property-table"><a-table-column title="属性" data-index="name" :width="150" fixed="left" /><a-table-column title="源码类型" :width="150"><template #default="{ record }"><a-tag>{{ record.typeName }}</a-tag><a-tag v-if="record.isNullable">可空</a-tag><a-tag v-if="typeHint(record)" color="purple">{{ typeHint(record) }}</a-tag></template></a-table-column><a-table-column title="展示名" :width="150"><template #default="{ record }"><a-input v-model:value="descriptor.properties[record.name].displayName" /></template></a-table-column><a-table-column title="说明" :width="180"><template #default="{ record }"><a-input v-model:value="descriptor.properties[record.name].description" /></template></a-table-column><a-table-column title="必填" :width="70"><template #default="{ record }"><a-switch v-model:checked="descriptor.properties[record.name].required" /></template></a-table-column><a-table-column title="长度" :width="90"><template #default="{ record }"><a-input-number v-model:value="descriptor.properties[record.name].maxLength" :min="1" /></template></a-table-column><a-table-column title="默认值" :width="120"><template #default="{ record }"><a-input v-model:value="descriptor.properties[record.name].defaultValue" /></template></a-table-column><a-table-column title="DTO" :width="65"><template #default="{ record }"><a-switch v-model:checked="descriptor.properties[record.name].dto" /></template></a-table-column><a-table-column title="创建" :width="65"><template #default="{ record }"><a-switch v-model:checked="descriptor.properties[record.name].create" /></template></a-table-column><a-table-column title="更新" :width="65"><template #default="{ record }"><a-switch v-model:checked="descriptor.properties[record.name].update" /></template></a-table-column><a-table-column title="筛选" :width="120"><template #default="{ record }"><a-select v-model:value="descriptor.properties[record.name].filter" allow-clear><a-select-option value="contains">包含</a-select-option><a-select-option value="equals">等于</a-select-option><a-select-option value="range">范围</a-select-option></a-select></template></a-table-column><a-table-column title="排序" :width="65"><template #default="{ record }"><a-switch v-model:checked="descriptor.properties[record.name].sortable" /></template></a-table-column></a-table></a-tab-pane><a-tab-pane key="advanced" tab="高级原文"><a-space class="raw-actions"><a-radio-group v-model:value="format"><a-radio-button value="yaml">YAML</a-radio-button><a-radio-button value="json">JSON</a-radio-button></a-radio-group><a-button :loading="saving" @click="saveRaw">保存原文并刷新计划</a-button></a-space><a-textarea v-model:value="raw" :auto-size="{ minRows: 18 }" class="raw-editor" /></a-tab-pane></a-tabs>
      <a-empty v-if="!plan" description="编辑属性后会自动保存并创建生成计划" /><a-row v-else :gutter="16" class="workspace"><a-col :span="9"><a-list bordered :data-source="plan.files"><template #renderItem="{ item }"><a-list-item :class="{ active: item.path === selectedPath }" @click="selectedPath = item.path"><a-tag :color="item.action === 'Conflict' ? 'red' : item.action === 'Update' ? 'orange' : item.action === 'Create' ? 'blue' : 'default'">{{ item.action }}</a-tag>{{ item.path }}</a-list-item></template></a-list></a-col><a-col :span="15"><a-tabs><a-tab-pane key="preview" tab="代码预览"><pre>{{ selectedFile?.content }}</pre></a-tab-pane><a-tab-pane key="diff" tab="当前 / 生成 Diff"><a-row :gutter="12"><a-col :span="12"><h3>当前</h3><pre>{{ selectedFile?.currentContent ?? '新文件' }}</pre></a-col><a-col :span="12"><h3>生成后</h3><pre>{{ selectedFile?.content }}</pre></a-col></a-row><p v-if="selectedFile?.diff">{{ selectedFile.diff }}</p></a-tab-pane></a-tabs></a-col></a-row>
    </a-layout-content></a-layout>
</template>

<style scoped>.studio { min-height: 100vh; }.studio h2,.project { padding: 0 16px; }.project { color: #666; font-size: 12px; overflow-wrap: anywhere; }.content { padding: 24px; }.alert,.top-tabs,.workspace { margin-top: 20px; }.property-table { margin-top: 16px; }.raw-actions { margin-bottom: 12px; }.raw-editor { font-family: Consolas, monospace; }.active { background: #e6f4ff; } pre { min-height: 420px; max-height: 70vh; overflow: auto; margin: 0; padding: 16px; background: #161b22; color: #e6edf3; border-radius: 6px; white-space: pre; }</style>
